set_property PACKAGE_PIN D5 [get_ports led_out_0]
set_property PACKAGE_PIN D6 [get_ports led_out_1]
set_property PACKAGE_PIN A5 [get_ports led_out_2]
set_property PACKAGE_PIN B5 [get_ports led_out_3]
set_property IOSTANDARD LVCMOS33 [get_ports led_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports led_out_2]
set_property IOSTANDARD LVCMOS33 [get_ports led_out_1]
set_property IOSTANDARD LVCMOS33 [get_ports led_out_3]
